### ISSUE TITLE
apollo-link-error networkError undefined 

### ISSUE THREAD

**Issue by bogdansoare** [apollographql/apollo-link#475] opened 2018-02-11 18:51 UTC
networkError is undefined when a network error occurs

apollo-link-error@1.0.5
apollo-link@1.1.0
apollo-link-http@1.3.3

The regression happened when upgrading apollo-link-http@1.3.2 to apollo-link-http@1.3.3

**Comment by evans** [comment] 2018-02-14 01:52
Thank you for the issue! Can you create a reproduction repo in code sandbox?

Ideally with a fetch that returns mock data.

**Comment by bogdansoare** [comment] 2018-02-14 21:19
@evans  sure, I can make a codesandox, but can you please explain what do you mean by a fetch that returns mock data?

**Comment by evans** [comment] 2018-02-20 22:59
@bogdansoare Thank you so much! I should have linked you in the first post. Sorry about that. [fetchMock](http://www.wheresrhys.co.uk/fetch-mock/) is what we use to test [apollo-link-http](https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link-http/src/__tests__/httpLink.ts#L40) and I think it would be super useful to the sandbox reproduction.

**Comment by webular** [comment] 2018-02-24 16:02
I'm having this same issue as well.  I get `networkError undefined`

Here is my code.
```
const errorLink = onError(operation => {
  const { networkError, graphQLErrors } = operation;
  console.log('graphQLErrors', graphQLErrors);
  console.log('networkError', networkError);

  if (networkError) {
    if (networkError.statusCode === 500) {
      console.log('Redirect to Login due to server disconnection.');
      // return logout();
    }

    console.log('networkError', networkError);
    if (networkError.statusCode === 401) {
      console.log('Redirect to Login due to unauthorize request.');
      // return logout();
    }
  }

  if (graphQLErrors && (graphQLErrors.auth === 'Invalid token') || (graphQLErrors.auth === 'Auth token expired') ) {
    // return logout();
  }
});

const AuthLink = (operation, forward) => {
  const token = store.get('auth-token');

  if (token) {
    operation.setContext(context => {
      let headers = context.headers;

      if (token) {
        headers = {
          ...context.headers,
          authorization: `Bearer ${token}`,
        };
      }

      return {
        ...context,
        headers,
      };
    });
  }

  return forward(operation);
};

const httpLink = new HttpLink({ uri: HTTP_URL });

const HTTPLink = ApolloLink.split(
  operation => {
    const operationAST = getOperationAST(
      operation.query,
      operation.operationName,
    );
    return !!operationAST && operationAST.operation === 'subscription';
  },
  new WebSocketLink({
    uri: WS_URL,
    options: {
      reconnect: true, //auto-reconnect
    },
  }),
  httpLink,
  // new BatchHttpLink({ uri: HTTP_URL, credentials: 'same-origin' }),
  env === 'developement' && apolloLogger,
);

const client = new ApolloClient({
  endpoint: HTTP_URL,
  link: from([errorLink, AuthLink, HTTPLink]),
  cache: new InMemoryCache({
    fragmentMatcher,
    dataIdFromObject: object => object.id,
  }),
});
```

**Comment by julestruong** [comment] 2018-03-02 14:34
Same here, any news ?

**Comment by webular** [comment] 2018-03-02 16:18
Nothing yet.  We got are currently hacking it by using `graphqlErrors` instead and looking for the graphql response, but this isn't ideal.

```
if (
    graphQLErrors &&
    (graphQLErrors.auth === 'Invalid token' ||
      graphQLErrors.auth === 'Auth token expired')
  ) {
    return logout();
  }
```

**Comment by tim-soft** [comment] 2018-03-02 23:39
https://github.com/apollographql/apollo-link/issues/422

Same here

**Comment by sheikalthaf** [comment] 2019-01-10 19:31
In angular 7, if i add any interceptors. i get this error

**Comment by JoviDeCroock** [comment] 2019-03-04 16:51
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.

**Closed by JoviDeCroock** 2019-03-04 16:51 UTC
Labels: bug
