### ISSUE TITLE
apollo-link-error DOMException when error encountered 

### ISSUE THREAD

**Issue by bogdansoare** [apollographql/apollo-link#196] opened 2017-10-31 19:53 UTC
I'm getting this message in the console when an error is encountered
```
DOMException: Failed to execute 'postMessage' on 'Window': Error: GraphQL error: Unknown argument 'firstNamez' on field 'updateUser' of type 'Mutation'. Did you mean 'firstName' or 'lastName'? (line 2, column 23):
  updateUser(id: $id, firstNamez: $firstName) {
                      ^ could not be cloned.
    at ApolloClient.hookLogger [as devToolsHookCb] (<anonymous>:14:14)
    at QueryManager.onBroadcast (http://localhost:3000/static/js/bundle.js:2983:27)
    at QueryManager../node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (http://localhost:3000/static/js/bundle.js:4056:14)
    at Object.complete (http://localhost:3000/static/js/bundle.js:3535:27)
    at SubscriptionObserver.complete (http://localhost:3000/static/js/bundle.js:122751:25)
    at SubscriptionObserver.complete (http://localhost:3000/static/js/bundle.js:122751:25)
    at SubscriptionObserver.complete (http://localhost:3000/static/js/bundle.js:122751:25)
    at http://localhost:3000/static/js/bundle.js:5170:26
    at <anonymous>
```

And it keeps appearing at every subsequent graphql request.

**Comment by jaydenseric** [comment] 2017-11-13 02:31
These sorts of console errors seem to happen when Apollo dev tools is running. I uninstalled dev tools and the errors went away.

**Comment by oliviertassinari** [comment] 2017-11-14 15:10
This sounds like a duplicate of https://github.com/apollographql/apollo-client-devtools/issues/64.

**Closed** 2018-02-15 18:28 UTC
