### ISSUE TITLE
Is something wrong with 1.2.7 release tag?

### ISSUE THREAD

**Issue by daveybrown** [apollographql/apollo-link#932] opened 2019-02-01 19:26 UTC
**Expected Behavior**

I was attempting to follow the Apollo Client [subscription setup guide](https://www.apollographql.com/docs/react/advanced/subscriptions.html#subscriptions-client)

`npm install --save apollo-link-ws subscriptions-transport-ws`

**Actual Behavior**

Install doesn't complete

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for apollo-link@^1.2.7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'apollo-link-ws'
npm ERR! notarget
```

**A _simple_ reproduction**

Run `npm install --save apollo-link-ws subscriptions-transport-ws` on a node project.

Mine was 

`{
  "name": "fetcher",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "start": "nodemon -e js,graphql -x node src/index.js",
    "dev": "nodemon -e js,graphql -x node --inspect src/index.js",
    "test": "jest",
    "deploy": "prisma deploy --env-file variables.env"
  },
  "dependencies": {
    "apollo-link": "1.2.6",
    "babel-preset-env": "^1.7.0",
    "dotenv": "6.0.0",
    "graphql": "^0.13.2",
    "graphql-cli": "^2.16.7",
    "graphql-request": "^1.8.2",
    "graphql-yoga": "^1.17.1",
    "nodemon": "^1.18.7",
    "npm-run-all": "^4.1.5",
    "prisma": "^1.24.0",
    "prisma-binding": "2.1.6"
  },
  "babel": {
    "presets": [
      "env"
    ]
  }
}
`

**Additional information**

The info page at https://npm.runkit.com/apollo-link shows v 1.2.7.

Clicking the test with runkit, starts a project with the previous version of 1.2.6

**Comment by benjamn** [comment] 2019-02-01 19:36
This seems to be an npm problem. We were hoping their replication would catch up by now, but we will probably need to republish these packages since the problem hasn't fixed itself.

**Comment by hwillson** [comment] 2019-02-01 20:07
@daveybrown We've republished using `apollo-link@1.2.8`. Can you try updating to see if that helps?

**Comment by davidcai** [comment] 2019-02-01 20:22
@hwillson 1.2.8 has the same issue: "Couldn't find any versions for apollo-link that matches ^1.2.8"

**Comment by hwillson** [comment] 2019-02-01 21:35
Very bizarre @davidcai - I can `npm/yarn install` 1.2.8 without any issues. Maybe an npm caching issue? Can anyone else on this thread install `apollo-link@1.2.8`?

**Comment by daveybrown** [comment] 2019-02-01 22:17
@hwillson `npm install --save apollo-link-ws subscriptions-transport-ws` installed w/o the previous error. But, when I look in packages.json, `^1.2.6` has been installed.

Next, I tried `npm install --save apollo-link@1.2.8`, which worked correctly.

Thanks for the quick fix (I assume it's fixed for everyone, but caching may affect some for a while)! Have a good weekend all! Peace

**Comment by davidcai** [comment] 2019-02-02 02:35
@daveybrown @hwillson Confirmed. `npm install apollo-link@^1.2.8` installed 1.2.8 correctly. Guess it is fixed on npm side.

**Comment by JoviDeCroock** [comment] 2019-02-09 20:51
Closing this since it seems resolved.

**Closed by JoviDeCroock** 2019-02-09 20:51 UTC
