### ISSUE TITLE
Calling XMLHttpRequest gives an error

### ISSUE THREAD

**Issue by vvaldersteins** [apollographql/apollo-link#317] opened 2017-12-06 14:14 UTC
Hi,

Whenever XMLHttpRequest() is called it gives an graphQL error:

`
Error: Network error: Cannot read property 'length' of null
    at new ApolloError (ApolloError.js:34)
    at eval (QueryManager.js:277)
    at eval (QueryManager.js:664)
    at Array.forEach (<anonymous>)
    at eval (QueryManager.js:663)
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (QueryManager.js:658)
    at eval (QueryManager.js:226)
    at ZoneDelegate.invoke (zone.js:392)
    at Object.onInvoke (core.js:4630)
`

The XMLHttpRequest is not related to the graphql, it is just to retrieve some additional data.

Is this already a known issue?

**Comment by jbaxleyiii** [comment] 2017-12-08 11:20
@vvaldersteins where are you making the request? How is it related to apollo link?

**Comment by vvaldersteins** [comment] 2017-12-08 11:24
@jbaxleyiii I'm making those requests when the first apollo request is done, when the page is loaded (using the apollo link middleware). as soon as I remove those requests from the middleware, it gives no errors.

**Comment by evans** [comment] 2018-02-15 21:40
@vvaldersteins Is this still an issue? If so, can you create a code sandbox similar to this [one](https://codesandbox.io/s/v69v13w0o0) or post a reproduction repository that will help use debug the issue?

**Comment by JoviDeCroock** [comment] 2019-03-04 16:50
Since this issue is really outdated I am closing it but if you are still concerned about this feel free to reopen and I'll get back to you asap.

**Closed by JoviDeCroock** 2019-03-04 16:50 UTC
Labels: bug
