### ISSUE TITLE
How to set token into onError ApolloClient?

### ISSUE THREAD

**Issue by huynguyen2903** [apollographql/apollo-link#1042] opened 2019-05-11 03:19 UTC
I want to handle error if return error will call setContext for query again but I can't get token in local state. How I can do that.
Thanks

```
import ApolloClient from "apollo-boost";
import { InMemoryCache } from "apollo-cache-inmemory";
import { setContext } from "apollo-link-context";
import { onError } from "apollo-link-error";
import { Observable, ApolloLink } from "apollo-link";
import { AsyncStorage } from "react-native";
import { defaults, resolvers } from "../resolvers";
import * as Api from "../Api";
import strings from "../../resources/string/strings";
import { showErrorDialog } from "../../tools/DialogHelper";


export default async () =>
  new ApolloClient({
    cache: new InMemoryCache({
      dataIdFromObject: object => object.key || null
    }),
    uri: Api.GRAPH_QL_URL,
    clientState: { defaults, resolvers },

    // cho handle network failed
    onError: ({ graphQLErrors, networkError, operation, forward }) => {
      
      if (networkError) {
        operation.setContext({
          headers: {
            Accept: "application/json",
            authorization: token !== null ? `JWT ${token}` : ""
          }
        });
      }
    },

    request: async operation => {
      const token = await AsyncStorage.getItem(strings.keyToken);

      console.log("Client request: ", {
        operationName: operation.operationName,
        variables: operation.variables,
        query: operation.query,
        jwtoken: token
      });
      operation.setContext({
        headers: {
          Accept: "application/json",
          authorization: token !== null ? `JWT ${token}` : ""
        }
      });
    },
  });
  
```

**Comment by JoviDeCroock** [comment] 2019-05-11 09:41
Hey, I think this is a duplicate of: https://github.com/apollographql/apollo-link/issues/646#issuecomment-479966447

Could you verify if this solves your problem?

**Closed** 2019-05-13 08:03 UTC
